function generateText(event) {
  event.preventDefault();

  let textElement = document.querySelector("#submited-text");

  new Typewriter("#submited-text", {
    strings: "Submited text generated by AI",
    autoStart: true,
    delay: 100,
    cursor: "",
  });
}

let textGeneratorElement = document.querySelector("#text-generator-form");
textGeneratorElement.addEventListener("submit", generateText);
